name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: ['3.7', '3.8']
    
    name: Python ${{ matrix.python-version }} Tests
    # name: Python 3.8 Tests

    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      # https://github.com/marketplace/actions/setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        # python-version: '3.8'
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install . 
    #   pip install -r requirements-dev.txt
    # - name: Lint with flake8
    #   run: |
    #     flake8 --ignore=F401 --exclude=$(grep -v '^#' .gitignore | xargs | sed -e 's/ /,/g')
    
    - name: Unit Test with pytest
      run: |
        pytest 
